### ISSUE TITLE
BID002 Product -- 69,269 DAI; $18,891 of HAUS

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-rfp#52]
### Bid Name

Keep September Boring

### Team Members

| Contributor   | Commitment % | HAUS%      | Value of $HAUS Denominated in USD  | $wxDAI     |
| ------------- | ------------ | ---------- | ---------------------------------- | ---------- |
|  adrienne     |  23%         |  10%       |     276        |   2,484    |
|  Avi          |  57%         |   5%       |     285        |   5,415    |
|  earth2travis | 100%         |  10%       |   1,200        |  10,800    |
|  Jord         | 100%         |  20%       |   2,400        |   9,600    |
|  JP           |  46%         |  20%       |     920        |   3,680    |
|  Santiago     |  80%         |  50%       |   4,000        |   4,000    |
|  Sam Kuhlmann | 100%         |   5%       |     600        |  11,400    |
|  Brian        | 100%         |   5%       |     500        |   9,500    |
|  Plor         |  46%         |  10%       |     460        |   4,140    |
|  Dekan Brown  |  80%         |  50%       |   4,800        |   4,800    |
|  Rowdy        |  69%         |  50%       |   3,450        |   3,450    |
|**Totals**     |**73%**       |**21%**     |**18,891**      |**69,269**  |

#### Related Objectives

- [OBJ001 -- Ship DAOhaus V3 #23](https://github.com/HausDAO/daohaus-rfp/issues/23)
- [OBJ002 -- Ensure DAOhaus v2 runs smoothly #24](https://github.com/HausDAO/daohaus-rfp/issues/24)
- [OBJ007 -- Strengthen our developer ecosystem #29](https://github.com/HausDAO/daohaus-rfp/issues/29)
- [OBJ009 -- Contribute to DAO public goods #31](https://github.com/HausDAO/daohaus-rfp/issues/31)

##### v2

- [testnet-transition](https://github.com/HausDAO/daohaus-app/milestone/9)
- [thegraph-replace](https://github.com/HausDAO/daohaus-app/milestone/6)

##### v3

- [core-ui-beta](https://github.com/HausDAO/daohaus-monorepo/milestone/3)
- [sdk-beta](https://github.com/HausDAO/daohaus-monorepo/milestone/10)
- [component-library-beta](https://github.com/HausDAO/daohaus-monorepo/milestone/11)
- [infra-beta](https://github.com/HausDAO/daohaus-monorepo/milestone/12)
- [testing-alpha](https://github.com/HausDAO/daohaus-monorepo/milestone/13)
- [docs-beta](https://github.com/HausDAO/daohaus-monorepo/milestone/14)

### Key Results and Activities

- Represent DAO at MCON
- Prepare DAO Toolbox for v1 Release (DevOps, Testing, Documentation)
- Prepare Summon, Hub and Admin for Handoff to Project Teams (Features, Testing, Fixes)
- Build WalletConnect Proposal
- Design and Scope Transaction Builder Library and App
- Complete Testnet Transition
- Create Mainnet Subgraph Migration Plan

### Budget

- **69,269** $wxDAI
- **$18,891** of HAUS

> *HAUS compensation properties
> 
>   - HAUS price will be set by 30 day TWAP at time of initial distribution 
>   - Must be locked for 12 months in Hedgey NFTs when distributed to individual contributors

### Receive Address (Gnosis Chain)

`0x23f6FA624581855D527df1Aa751B8a60c5e8059d`

### Timeline

September 1st through September 30th in the year of 2022

**Comment by slgraham** [comment]
@earth2travis are the HAUS in terms of `$ amounts of HAUS` or `number of HAUS tokens`? If the latter, can you include the HAUS price you're assuming?

**Comment by earth2travis** [comment]
@slgraham the calculations were made based on a number of HAUS tokens based on price from July TWAP of $5.75 USD.

**Comment by slgraham** [comment]
This Bid has explicitly gone against the designed template and removed any commitment to locking the HAUS. This should be remedied ASAP. During these months we are distributing a lot of HAUS and its needs to be locked to protect our ability to secure additional funding and to protect contributors who have demonstrated their commitment to and belief in DAOhaus by accepting a high percentage of HAUS.

**Comment by earth2travis** [comment]
| Contributor   | Commitment % | HAUS%      | Value of $HAUS Denominated in USD  | $wxDAI     |
| ------------- | ------------ | ---------- | ---------------------------------- | ---------- |
|  adrienne     |  23%         |  10%       |     276        |   2,484    |
|  Avi          |  57%         |   5%       |     285        |   5,415    |
|  earth2travis | 100%         |  10%       |   1,200        |  10,800    |
|  Jord         | 100%         |  20%       |   2,400        |   9,600    |
|  JP           |  46%         |  20%       |     920        |   3,680    |
|  Santiago     |  80%         |  50%       |   4,000        |   4,000    |
|  Sam Kuhlmann | 100%         |   5%       |     600        |  11,400    |
|  Brian        | 100%         |   5%       |     500        |   9,500    |
|  Plor         |  46%         |  10%       |     460        |   4,140    |
|  Dekan Brown  |  80%         |  50%       |   4,800        |   4,800    |
|  Rowdy        |  69%         |  50%       |   3,450        |   3,450    |
|**Totals**     |**73%**       |**21%**     |**18,891**      |**69,269**  |

**Comment by earth2travis** [comment]
@slgraham the title and Team Members table has been updated. The quote related to "HAUS compensation properties" has been added and the budget changed to $18,891 of HAUS.

**Comment by earth2travis** [comment]
- [Received 2,825.2738 HAUS](https://blockscout.com/xdai/mainnet/tx/0x301ae768cc91ba2bd489f0c8d80dc878077e2122a9340f184204852e8e0fb3ae/) on September 30, 2022
- [Received 69,269 WXDAI](https://blockscout.com/xdai/mainnet/tx/0xf406bef0fa26040af0c03074144bdd4b58e0e6d3ebd13ea961d41431395401e2/) on September 30, 2022

**Comment by earth2travis** [comment]
Sent 69,269 WXDAI on September 30, 2022

**Comment by earth2travis** [comment]
Locked 2,825.44 HAUS in Hedgy NFTs on October 31, 2022

https://gnosis-safe.io/app/gno:0x23f6FA624581855D527df1Aa751B8a60c5e8059d/transactions/multisig_0x23f6FA624581855D527df1Aa751B8a60c5e8059d_0x42ca766e6b5ee8287a1075dda471e61f2be724c72234629a0fb306664e58062b

**Comment by earth2travis** [comment]
https://blockscout.com/xdai/mainnet/tx/0x231c814be50db5c717df54fc3992e2e44f283fd767f0c1bfe723546902b1f0fd
