### ISSUE TITLE
RFP001 (Product): BID001 2mo 55,064DAI 8,835HAUS

### ISSUE THREAD

**Issue by dekanbro** [HausDAO/daohaus-rfp#7]
In response to

RFP: #1 
Forum: [Product Epoch Request For Proposal 001](https://forum.daohaus.club/t/product-epoch-request-for-proposal-001/11181)

Please note, this is a proposal not a detailed project plan. More specifics around features and scope will be determined after funding is approved.

## Overview

This proposal seeks to obtain the funding required for the completion of the core v3 product offering while maintaining and decentralizing DAOhaus App v2.

This work takes place between July 11 - September 2 in the year of 2022.

The propsal addresses the two highest priority objectives from the [DAOhaus Collective Projection of Relative Importance of Objectives (v0.2)](https://docs.google.com/spreadsheets/d/1i6xLojEIv86GpALSzsPGtTyWUL_gU9Nq0OkM6K-NNVE/edit?resourcekey&pli=1#gid=2118289412) survey.

- Ship DAOhaus v3
- Ensure DAOhaus v2 runs smoothly

These deliverables provide the foundation of the future of DAOhaus. We are also shipping open-source software that can be considered a public good.

## Goals

- Deploy v3 contracts and subgraphs
- Release* v1 of Haus Infrastructure
- Release* beta version of DAOhaus App v3
- Release* v1 of Haus Libraries
- Release v1 of documention site
- Provide results of testing

`*` Release includes tested and documented code.

### Contracts* and Subgraphs

- Deploy Baal contracts and subgraphs to the following networks:
    - Goerli
    - Gnosis Chain
    - Mainnet
    - Arbitrum
    - Optimism

`*` Contracts will only be audited if MolochMystics are willing to cover costs.

### Haus Infrastructure v1

- Helm charts
- Kubernetes playbook
- Ceramic node
- Subgraph node
- Jobs

### Haus Libraries v1

Publish all packages to NPM

#### Utility

- SDK
- Commons

#### Feature

- DAOhaus Connect

#### Component

- Storybook

### DAOhaus App v2

- Ongoing support, bug fixes, maintenance
- Replace Airtable with Poster metadata

### DAOhaus App v3

Deploy functional interfaces to subdomains.

- Summoner beta
- Hub beta
- Core UI beta

### Documentation Site*

Site(s) containing documentation for contracts, subgraphs, infrastructure and libraries.

`*` Does not include user facing documentation for DAOhaus App v2 or v3.

### Test Results

Report with overview and status of manual and automated testing results.

## Budget

**Requested Amount**:
- $HAUS: 17,670
- $wxDAI: 110,128

### Monthly Breakdown

| Contributor  | Primary Role       | Commitment % | Level | Cash Equivalent | $HAUS % | $HAUS     | $wxDAI     |
| ------------ | ------------------ | ------------ | ----- | --------------- | ------- | --------- | ---------- |
| adrienne     | Designooor         | 80%          | 5     | 9,600           | 13.54%  | 243       | 8300       |
| Avi          | Designooor         | 57%          | 4     | 5,700           | 36.84%  | 393       | 3600       |
| earth2travis | Project Managooor  | 100%         | 5     | 12,000          | 25.00%  | 562       | 9000       |
| Jord         | Developooor        | 100%         | 5     | 12,000          | 55.00%  | 1237      | 5400       |
| JP           | Project Managooor  | 69%          | 4     | 6,900           | 42.03%  | 543       | 4000       |
| Keating      | Developooor        | 23%          | 5     | 2,760           | 10.00%  | 51        | 2484       |
| Santiago     | Developooor        | 69%          | 4     | 6,900           | 69.57%  | 900       | 2100       |
| Sam Kuhlmann | Developooor        | 100%         | 5     | 12,000          | 33.33%  | 750       | 8000       |
| Brian        | Developooor        | 100%         | 4     | 10,000          | 75.00%  | 1406      | 2500       |
| Plor         | Project Managooor  | 46%          | 4     | 4,600           | 20.00%  | 172       | 3680       |
| Dekan Brown  | Developooor        | 75%          | 5     | 9,000           | 33.33%  | 562       | 6000       |
| Jeremy       | Testooor           | 23%          | 4     | 2,300           | 100.00% | 431       | 0          |
| Scott        | Developooor        | 23%          | 5     | 2,760           | 100.00% | 517       | 0          |
| TW           | Documentooor       | 57%          | 4     | 5,700           | 100.00% | 1068      | 0          |
| **Totals**   |                    |              |       | **102,220**     |         | **8,835** | **55,064** |

## Details

- **Due Date**: September 2, 2022
- **Primary Contact**: Ξ2T
- **DAO Address**: `0x23f6FA624581855D527df1Aa751B8a60c5e8059d`

**Comment by scottrepreneur** [comment]
I am not committing for July at the outlined percentage.

**Comment by earth2travis** [comment]
- Received 110,128 WXDAI on JUL 23, 2022
- Sent 55,064 WXDAI on AUG 1, 2022
- Received 8,835 HAUS on AUG 8, 2022
- Sent 55,064 WXDAI on SEP 1, 2022
- Sent 8,700 HAUS on SEP 1, 2022

https://gnosis-safe.io/app/gno:0x23f6FA624581855D527df1Aa751B8a60c5e8059d/transactions/history

**Comment by earth2travis** [comment]
Locked 7,767 HAUS (for August payments) in Hedgy NFTs on October 31, 2022

https://blockscout.com/xdai/mainnet/address/0x40A2aCCbd92BCA938b02010E17A5b8929b49130D/transactions#address-tabs

That should complete this issue
